// app/privacy/page.js

import Link from "next/link";

export const metadata = {
  title: "Privacy Policy",
  description: "What Daily AI Pulse collects, why, and how to exercise your GDPR rights.",
};

export default function PrivacyPage() {
  return (
    <div className="mx-auto max-w-3xl px-6 py-16">
      <h1 className="text-3xl font-bold tracking-tight text-zinc-900">Privacy Policy</h1>
      <p className="mt-2 text-sm text-zinc-500">Last updated: August 15, 2026</p>

      <div className="mt-8 space-y-8 text-zinc-700 [&_h2]:mt-2 [&_h2]:font-semibold [&_h2]:text-zinc-900 [&_p]:mt-2 [&_ul]:mt-2 [&_ul]:list-disc [&_ul]:pl-5 [&_li]:mt-1">
        <section>
          <h2>Who we are</h2>
          <p>
            Daily AI Pulse is operated by Jeevan Merkaji Somanna, an individual based in
            Germany. Full contact details are on the{" "}
            <Link href="/impressum" className="underline underline-offset-4">
              Impressum
            </Link>{" "}
            page. For anything related to this policy, you can reach us at{" "}
            <a href="mailto:privacy@getdailyaipulse.com" className="underline underline-offset-4">
              privacy@getdailyaipulse.com
            </a>
            .
          </p>
        </section>

        <section>
          <h2>What we collect</h2>
          <ul>
            <li>
              <strong>Email address</strong> — required to sign up, log in, and receive the
              daily story.
            </li>
            <li>
              <strong>Topic preference</strong> — which subject you&apos;d like your daily
              story about.
            </li>
            <li>
              <strong>Subscription status</strong> — whether your daily email is active, and
              whether you&apos;re on the Free or Pro plan.
            </li>
            <li>
              <strong>Login and session data</strong> — a short-lived, single-use login token
              when you request a login link, and a session identifier stored in an
              HttpOnly cookie once you&apos;re signed in.
            </li>
            <li>
              <strong>Billing information</strong> — if you upgrade to Pro, Stripe processes
              your payment details directly. We only store your Stripe customer and
              subscription IDs, never your card number.
            </li>
            <li>
              <strong>Basic server logs</strong> — standard technical logs (e.g. IP address,
              timestamps) generated by our hosting provider as part of operating the
              website.
            </li>
          </ul>
          <p>
            We don&apos;t use advertising or analytics cookies, and we don&apos;t track you
            across other websites.
          </p>
        </section>

        <section>
          <h2>Why we process it, and on what legal basis</h2>
          <ul>
            <li>
              To create your account and send the daily story you signed up for — necessary
              to perform our contract with you (Art. 6(1)(b) GDPR).
            </li>
            <li>
              To process Pro plan payments and manage your subscription — necessary to
              perform our contract with you (Art. 6(1)(b) GDPR).
            </li>
            <li>
              To keep the service secure and working correctly (e.g. session cookies,
              server logs) — our legitimate interest in operating a reliable service (Art.
              6(1)(f) GDPR).
            </li>
          </ul>
        </section>

        <section>
          <h2>Who we share it with</h2>
          <p>We use the following processors to run the service. None of them are permitted to use your data for their own purposes.</p>
          <ul>
            <li><strong>Neon</strong> — hosts our database.</li>
            <li>
              <strong>Anthropic</strong> — generates the daily story summaries. Anthropic
              only receives the day&apos;s news headlines and articles, never your email
              address or account data.
            </li>
            <li>
              <strong>Resend</strong> — delivers our emails (signup confirmations, daily
              stories, login links). Configured to process data in the EU (Ireland).
            </li>
            <li>
              <strong>Stripe</strong> — handles Pro plan payments and billing. Stripe is
              PCI-DSS certified; we never see or store your full card details.
            </li>
            <li><strong>Vercel</strong> — hosts the website and runs our daily scheduled job.</li>
          </ul>
          <p>
            Some of these providers may process data outside the European Economic Area
            (e.g. in the United States). Where that happens, they do so under appropriate
            safeguards required by GDPR Chapter V, such as the EU–U.S. Data Privacy
            Framework or Standard Contractual Clauses.
          </p>
        </section>

        <section>
          <h2>How long we keep it</h2>
          <p>
            We keep your account data for as long as your account is active. If you
            unsubscribe, we stop sending you emails but may keep a minimal record (e.g.
            your email address and unsubscribe status) to honor that choice and to avoid
            emailing you again by mistake. To have your account and data deleted entirely,
            email{" "}
            <a href="mailto:privacy@getdailyaipulse.com" className="underline underline-offset-4">
              privacy@getdailyaipulse.com
            </a>
            . Published daily stories themselves (the news content, not tied to any
            individual subscriber) are kept indefinitely as a public archive.
          </p>
        </section>

        <section>
          <h2>Your rights</h2>
          <p>Under GDPR, you have the right to:</p>
          <ul>
            <li>Access the personal data we hold about you</li>
            <li>Correct inaccurate data</li>
            <li>Request deletion of your data</li>
            <li>Restrict or object to certain processing</li>
            <li>Receive your data in a portable format</li>
            <li>Withdraw consent at any time, where processing is based on consent</li>
            <li>
              Lodge a complaint with a data protection supervisory authority — in Germany,
              your state&apos;s Landesdatenschutzbehörde
            </li>
          </ul>
          <p>
            To exercise any of these, email{" "}
            <a href="mailto:privacy@getdailyaipulse.com" className="underline underline-offset-4">
              privacy@getdailyaipulse.com
            </a>
            .
          </p>
        </section>

        <section>
          <h2>Cookies</h2>
          <p>
            We use a single essential, HttpOnly session cookie to keep you signed in. It&apos;s
            required for the account and billing features to work and isn&apos;t used for
            tracking or advertising.
          </p>
        </section>

        <section>
          <h2>Children</h2>
          <p>Daily AI Pulse is intended for business owners and professionals, not children. We don&apos;t knowingly collect data from anyone under 16.</p>
        </section>

        <section>
          <h2>Changes to this policy</h2>
          <p>
            If we make material changes, we&apos;ll update the date at the top of this page
            and, where appropriate, notify active subscribers by email.
          </p>
        </section>
      </div>
    </div>
  );
}
